2015-09-15 10:53:22 开始运行爬虫----------niwodai---------------------------------------
2015-09-15 10:53:25+0800 [scrapy] INFO: Scrapy 0.24.4 started (bot: niwodai)
2015-09-15 10:53:25+0800 [scrapy] INFO: Optional features available: ssl, http11, boto, django
2015-09-15 10:53:25+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'niwodai.spiders', 'SPIDER_MODULES': ['niwodai.spiders'], 'BOT_NAME': 'niwodai'}
2015-09-15 10:53:25+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2015-09-15 10:53:26+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-09-15 10:53:26+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-09-15 10:53:26+0800 [scrapy] INFO: Enabled item pipelines: NiwodaiPipeline
2015-09-15 10:53:26+0800 [niwodai] INFO: Spider opened
2015-09-15 10:53:26+0800 [niwodai] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:53:26+0800 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6026
2015-09-15 10:53:26+0800 [scrapy] DEBUG: Web service listening on 127.0.0.1:6083
2015-09-15 10:53:27+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZwJkBTcFPABiU2A=.html> (referer: None)
2015-09-15 10:53:27+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZwJkBTcFPABiU2A=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:31+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJnBTQFNABvU2c=.html> (referer: None)
2015-09-15 10:53:31+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJnBTQFNABvU2c=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:33+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJjBTIFPQBlU2I=.html> (referer: None)
2015-09-15 10:53:33+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJjBTIFPQBlU2I=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:36+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJiBTQFNABhU2U=.html> (referer: None)
2015-09-15 10:53:36+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJiBTQFNABhU2U=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:39+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFMgBiU2U=.html> (referer: None)
2015-09-15 10:53:39+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFMgBiU2U=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:43+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJsBTIFMgBuU2c=.html> (referer: None)
2015-09-15 10:53:43+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJsBTIFMgBuU2c=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:47+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCaAJiBTIFMQBmU2Q=.html> (referer: None)
2015-09-15 10:53:47+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCaAJiBTIFMQBmU2Q=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:51+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJjBTEFPABkU2U=.html> (referer: None)
2015-09-15 10:53:51+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJjBTEFPABkU2U=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:54+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBmU24=.html> (referer: None)
2015-09-15 10:53:54+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBmU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:53:58+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCYQJjBTMFNwBiU2Q=.html> (referer: None)
2015-09-15 10:53:58+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCYQJjBTMFNwBiU2Q=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:02+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJtBTEFNwBiU24=.html> (referer: None)
2015-09-15 10:54:02+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJtBTEFNwBiU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:07+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZgJsBTYFNQBiU24=.html> (referer: None)
2015-09-15 10:54:07+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZgJsBTYFNQBiU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:11+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTEFMQBuU2U=.html> (referer: None)
2015-09-15 10:54:11+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTEFMQBuU2U=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:15+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPABmU2E=.html> (referer: None)
2015-09-15 10:54:15+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPABmU2E=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:18+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZgJjBT4FMQBiU2M=.html> (referer: None)
2015-09-15 10:54:18+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZgJjBT4FMQBiU2M=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:22+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJgBT8FNwBlU2c=.html> (referer: None)
2015-09-15 10:54:22+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJgBT8FNwBlU2c=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:26+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTMFPABvU2Q=.html> (referer: None)
2015-09-15 10:54:26+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTMFPABvU2Q=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:26+0800 [niwodai] INFO: Crawled 17 pages (at 17 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:54:29+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJjBTQFMABhU2E=.html> (referer: None)
2015-09-15 10:54:29+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJjBTQFMABhU2E=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:33+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJjBTcFNQBgU24=.html> (referer: None)
2015-09-15 10:54:33+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJjBTcFNQBgU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:36+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJlBTYFPABvU24=.html> (referer: None)
2015-09-15 10:54:36+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJlBTYFPABvU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:41+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJiBTQFNABvU24=.html> (referer: None)
2015-09-15 10:54:41+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJiBTQFNABvU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:44+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCYgJjBTEFNwBlU2U=.html> (referer: None)
2015-09-15 10:54:44+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCYgJjBTEFNwBlU2U=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:48+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJsBT4FNwBiU24=.html> (referer: None)
2015-09-15 10:54:48+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJsBT4FNwBiU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:52+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYQJjBTQFPABjU24=.html> (referer: None)
2015-09-15 10:54:52+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYQJjBTQFPABjU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:55+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJiBTQFNwBuU2A=.html> (referer: None)
2015-09-15 10:54:55+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJiBTQFNwBuU2A=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:59+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJsBTYFMABlU2Y=.html> (referer: None)
2015-09-15 10:54:59+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJsBTYFMABlU2Y=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:01+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBhU2I=.html> (referer: None)
2015-09-15 10:55:01+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBhU2I=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:06+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFMgBhU2M=.html> (referer: None)
2015-09-15 10:55:06+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFMgBhU2M=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:09+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJjBTIFNwBlU2I=.html> (referer: None)
2015-09-15 10:55:09+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJjBTIFNwBlU2I=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:13+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACaAJgBTYFPABvU2c=.html> (referer: None)
2015-09-15 10:55:13+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACaAJgBTYFPABvU2c=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:17+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJkBTQFNQBiU2E=.html> (referer: None)
2015-09-15 10:55:17+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJkBTQFNQBiU2E=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:20+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBiU2c=.html> (referer: None)
2015-09-15 10:55:20+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBiU2c=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:23+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJtBTUFNwBiU24=.html> (referer: None)
2015-09-15 10:55:23+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJtBTUFNwBiU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:26+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJnBTAFMABhU2U=.html> (referer: None)
2015-09-15 10:55:26+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJnBTAFMABhU2U=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:26+0800 [niwodai] INFO: Crawled 34 pages (at 17 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:55:30+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJmBTEFNABvU24=.html> (referer: None)
2015-09-15 10:55:30+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJmBTEFNABvU24=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:33+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJsBTMFNwBhU28=.html> (referer: None)
2015-09-15 10:55:33+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJsBTMFNwBhU28=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:38+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTIFMwBuU2M=.html> (referer: None)
2015-09-15 10:55:38+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTIFMwBuU2M=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:41+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJtBTUFNgBjU2A=.html> (referer: None)
2015-09-15 10:55:41+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJtBTUFNgBjU2A=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:43+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJhBTAFMwBjU2c=.html> (referer: None)
2015-09-15 10:55:43+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJhBTAFMwBjU2c=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:47+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTUFPQBjU2I=.html> (referer: None)
2015-09-15 10:55:47+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTUFPQBjU2I=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:50+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCaAJgBTMFNABhU2Q=.html> (referer: None)
2015-09-15 10:55:50+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCaAJgBTMFNABhU2Q=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:53+0800 [niwodai] DEBUG: Crawled (200) <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJkBTcFNwBlU2I=.html> (referer: None)
2015-09-15 10:55:53+0800 [niwodai] ERROR: Spider error processing <GET https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJkBTcFNwBlU2I=.html>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/scrapy/crawl/niwodai/niwodai/spiders/base.py", line 57, in parse
	    item['description'] = sel.xpath('//p[@class=\"fc_6 text\"]/text()').extract()[0]
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:53+0800 [niwodai] INFO: Closing spider (finished)
2015-09-15 10:55:53+0800 [niwodai] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 18976,
	 'downloader/request_count': 42,
	 'downloader/request_method_count/GET': 42,
	 'downloader/response_bytes': 719403,
	 'downloader/response_count': 42,
	 'downloader/response_status_count/200': 42,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 9, 15, 2, 55, 53, 988277),
	 'log_count/DEBUG': 44,
	 'log_count/ERROR': 42,
	 'log_count/INFO': 9,
	 'response_received_count': 42,
	 'scheduler/dequeued': 42,
	 'scheduler/dequeued/memory': 42,
	 'scheduler/enqueued': 42,
	 'scheduler/enqueued/memory': 42,
	 'spider_exceptions/IndexError': 42,
	 'start_time': datetime.datetime(2015, 9, 15, 2, 53, 26, 783332)}
2015-09-15 10:55:53+0800 [niwodai] INFO: Spider closed (finished)
['https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZgJsBTYFNQBiU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJjBTcFNQBgU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJnBTQFNABvU2c=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJsBT4FNwBiU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCaAJkBTQFNQBiU2E=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCYQJjBTMFNwBiU2Q=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCaAJiBTIFMQBmU2Q=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJtBTEFNwBiU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCYgJjBTEFNwBlU2U=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJkBTcFNwBlU2I=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTMFPABvU2Q=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTIFMwBuU2M=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJjBTIFNwBlU2I=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJjBTEFPABkU2U=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJsBTYFMABlU2Y=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCYwJsBTIFMgBuU2c=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWUCZQJmBTEFNABvU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTUFPQBjU2I=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWYCZQJnBTEFMQBuU2U=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJlBTYFPABvU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJiBTQFNABvU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWcCaAJgBTMFNABhU2Q=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYQJjBTQFPABjU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJgBT8FNwBlU2c=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJiBTQFNwBuU2A=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJhBTAFMwBjU2c=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJiBTQFNABhU2U=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJnBTAFMABhU2U=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFMgBiU2U=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJjBTIFPQBlU2I=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYwJjBTQFMABhU2E=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACYAJsBTMFNwBhU28=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFMgBhU2M=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBmU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBiU2c=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPQBhU2I=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJsBTYFPABmU2E=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJtBTUFNwBiU24=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZAJtBTUFNgBjU2A=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZwJkBTcFPABiU2A=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACZgJjBT4FMQBiU2M=.html', 'https://member.niwodai.com/xiangmu/v-ADZUNlYwVTkFY1RgUDBeaQo6VWACaAJgBTYFPABvU2c=.html']
2015-09-15 10:56:04 爬取结束-------------niwodai---------------------------------------
