2015-09-14 14:27:22 开始运行爬虫----------paipaidai---------------------------------------
2015-09-14 14:27:24+0800 [scrapy] INFO: Scrapy 0.24.4 started (bot: paipaidai)
2015-09-14 14:27:24+0800 [scrapy] INFO: Optional features available: ssl, http11, boto, django
2015-09-14 14:27:24+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'paipaidai.spiders', 'SPIDER_MODULES': ['paipaidai.spiders'], 'BOT_NAME': 'paipaidai'}
2015-09-14 14:27:25+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2015-09-14 14:27:26+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-09-14 14:27:26+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-09-14 14:27:27+0800 [scrapy] INFO: Enabled item pipelines: PaipaidaiPipeline
2015-09-14 14:27:27+0800 [paipaidai] INFO: Spider opened
2015-09-14 14:27:27+0800 [paipaidai] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-09-14 14:27:27+0800 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-09-14 14:27:27+0800 [scrapy] DEBUG: Web service listening on 127.0.0.1:6080
2015-09-14 14:27:27+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/12_s0_p1>
2015-09-14 14:27:34+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/12_s0_p2>
2015-09-14 14:27:37+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/13_s0_p1>
2015-09-14 14:27:39+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/13_s0_p2>
2015-09-14 14:27:41+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/14_s0_p1>
2015-09-14 14:27:43+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/8_s0_p2> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:44+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/14_s0_p2>
2015-09-14 14:27:45+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/3_s0_p1> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:46+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/8_s0_p1>
2015-09-14 14:27:52+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/3_s0_p2>
2015-09-14 14:27:55+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/15_s0_p1>
2015-09-14 14:27:57+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/16_s0_p2> (failed 1 times): 503 Service Unavailable
2015-09-14 14:27:58+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/15_s0_p2>
2015-09-14 14:27:59+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/16_s0_p1>
2015-09-14 14:28:04+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:06+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:06+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:09+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:09+0800 [paipaidai] DEBUG: Filtered duplicate request: <GET http://www.ppdai.com/list/4182242> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2015-09-14 14:28:11+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/8_s0_p2> (failed 2 times): 503 Service Unavailable
2015-09-14 14:28:13+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:13+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:18+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:21+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:21+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/3_s0_p1>
2015-09-14 14:28:23+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:25+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/16_s0_p2> (failed 2 times): 503 Service Unavailable
2015-09-14 14:28:27+0800 [paipaidai] INFO: Crawled 4 pages (at 4 pages/min), scraped 0 items (at 0 items/min)
2015-09-14 14:28:28+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:30+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-14 14:28:33+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4091914> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:33+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4091914>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:35+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4150449> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:35+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4150449>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:38+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4043871> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:38+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4043871>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:40+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4104369> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:40+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4104369>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:46+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4124938> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:46+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4124938>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:47+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4124481> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:47+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4124481>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:48+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:50+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4215152> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:28:50+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4215152>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:28:55+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:28:58+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:01+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:02+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:04+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:05+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4186674> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:05+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4186674>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:09+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:10+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4185554> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:10+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4185554>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:11+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:13+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4222360> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:13+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4222360>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:15+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/3919008> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:15+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/3919008>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:17+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4225589> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:17+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4225589>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:20+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4006181> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:20+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4006181>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:23+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4182242> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:23+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4182242>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:25+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4222449> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:25+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4222449>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:27+0800 [paipaidai] INFO: Crawled 27 pages (at 23 pages/min), scraped 0 items (at 0 items/min)
2015-09-14 14:29:28+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4146620> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:28+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4146620>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:30+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4047346> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:30+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4047346>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:33+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4012330> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:33+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4012330>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:35+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/3962278> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:36+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/3962278>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:38+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4145838> (referer: http://invest.ppdai.com/loan/list)
2015-09-14 14:29:38+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4145838>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-14 14:29:41+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/16_s0_p2>
2015-09-14 14:29:43+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/8_s0_p2>
2015-09-14 14:29:45+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:48+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-14 14:29:48+0800 [paipaidai] INFO: Closing spider (finished)
2015-09-14 14:29:48+0800 [paipaidai] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 15957,
	 'downloader/request_count': 60,
	 'downloader/request_method_count/GET': 60,
	 'downloader/response_bytes': 291509,
	 'downloader/response_count': 60,
	 'downloader/response_status_count/200': 34,
	 'downloader/response_status_count/302': 14,
	 'downloader/response_status_count/503': 12,
	 'dupefilter/filtered': 120,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 9, 14, 6, 29, 48, 966067),
	 'log_count/DEBUG': 63,
	 'log_count/ERROR': 20,
	 'log_count/INFO': 9,
	 'request_depth_max': 1,
	 'response_received_count': 34,
	 'scheduler/dequeued': 60,
	 'scheduler/dequeued/memory': 60,
	 'scheduler/enqueued': 60,
	 'scheduler/enqueued/memory': 60,
	 'spider_exceptions/IndexError': 20,
	 'start_time': datetime.datetime(2015, 9, 14, 6, 27, 27, 44423)}
2015-09-14 14:29:48+0800 [paipaidai] INFO: Spider closed (finished)
2015-09-14 14:29:59 爬取结束-------------paipaidai---------------------------------------
